/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_gwu_rpg_androidnodecam_AndNodeCam */

#ifndef _Included_edu_gwu_rpg_androidnodecam_AndNodeCam
#define _Included_edu_gwu_rpg_androidnodecam_AndNodeCam
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_gwu_rpg_androidnodecam_AndNodeCam
 * Method:    sendData
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_edu_gwu_rpg_androidnodecam_AndNodeCam_sendData
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     edu_gwu_rpg_androidnodecam_AndNodeCam
 * Method:    Initialize
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_edu_gwu_rpg_androidnodecam_AndNodeCam_Initialize
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     edu_gwu_rpg_androidnodecam_AndNodeCam
 * Method:    InitializeLogger
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_gwu_rpg_androidnodecam_AndNodeCam_InitializeLogger
  (JNIEnv *, jobject);

/*
 * Class:     edu_gwu_rpg_androidnodecam_AndNodeCam
 * Method:    logCamData
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_edu_gwu_rpg_androidnodecam_AndNodeCam_logCamData
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     edu_gwu_rpg_androidnodecam_AndNodeCam
 * Method:    logIMUData
 * Signature: (FFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_edu_gwu_rpg_androidnodecam_AndNodeCam_logIMUData
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     edu_gwu_rpg_androidnodecam_AndNodeCam
 * Method:    stopLogging
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_gwu_rpg_androidnodecam_AndNodeCam_stopLogging
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
